

#include <stdio.h>
#include <stdlib.h>

/*
 * Workaround for a but in boost 1.58: It does not support
 * empty structs in BOOST_FUSION_ADOPT_STRUCT
 */
#undef BOOST_PP_VARIADICS
#define BOOST_PP_VARIADICS 0

#include <vault-unify-parser.hpp>

#include <vault-unify-clause-standard.hpp>

#include <vault-unify-debug.hpp>

namespace vault {
namespace unify {
namespace PrologParser {

int ClauseContext::m_anonClauseIndex;

namespace {

/**
 * Collect the distinct VarTerms reachable from pTerm, in first-encounter
 * order (an otherwise-arbitrary but deterministic-within-one-call order),
 * skipping anything already in out_visited. Used by
 * AnyTermFactory::operator()(IfStatementInput) to find the free variables
 * of an `if` statement's cond+body -- see there for why they need to be
 * collected up front (to build each synthesized clause's own fresh
 * variables via cloneTermTree(), and the call-site term left in the
 * enclosing goal chain).
 *
 * pTerm's actual VarTerm nodes are not const in memory (they live on as
 * ordinary VarTerm* in ClauseContext::m_mapSymbols and are reused directly
 * at the if-statement's call site); the const-qualified traversal here
 * only matches collectTermTree()'s style, so the const is cast away when
 * a VarTerm is found and stored.
 */
void collectVarTermsOrdered(
        const vault::unify::AbstractTerm* pTerm,
        std::set<const vault::unify::AbstractTerm*>& out_visited,
        std::vector<vault::unify::VarTerm*>& out_vars )
{
    if( !pTerm ) {
        return;
    }
    if( !out_visited.insert( pTerm ).second ) {
        return;
    }
    if( const vault::unify::VarTerm* pVarTerm = dynamic_cast<const vault::unify::VarTerm*>( pTerm ) ) {
        out_vars.push_back( const_cast<vault::unify::VarTerm*>( pVarTerm ) );
        return;
    }
    vault::unify::AbstractTermIterator* pIt = pTerm->abstractTermIterator();
    if( pIt ) {
        while( pIt->isValid() ) {
            const vault::unify::TermTraversable* pChildTraversable = pIt->getTermTraversable();
            if( pChildTraversable ) {
                const vault::unify::AbstractTerm* pChildTerm =
                    dynamic_cast<const vault::unify::AbstractTerm*>( pChildTraversable );
                if( pChildTerm ) {
                    collectVarTermsOrdered( pChildTerm, out_visited, out_vars );
                }
            }
            pIt->next();
        }
        delete pIt;
    }
}

/**
 * Delete the structural (non-VarTerm) nodes of a scratch term tree built
 * by AnyTermFactory::operator()(IfStatementInput) while assembling an
 * `if` statement's cond+body via the enclosing ClauseContext -- once
 * cloneTermTree() has copied that scratch tree into a synthesized clause,
 * the ConsTerm/MapTerm scaffolding is no longer referenced from anywhere
 * and must be freed here, or it leaks.
 *
 * VarTerm leaves are deliberately left alone (not deleted, not recursed
 * into -- they are always leaves): every VarTerm reachable from cond+body
 * is, by construction, exactly one of the "free variables" collected by
 * collectVarTermsOrdered() above, which the if-statement's call-site term
 * reuses directly. That call-site term becomes part of the enclosing
 * clause/query's own tree, so those VarTerms must survive along with it --
 * deleting them here would leave the call site holding a dangling pointer.
 */
void deleteScratchTermTree(
        const vault::unify::AbstractTerm* pTerm,
        std::set<const vault::unify::AbstractTerm*>& out_visited )
{
    if( !pTerm ) {
        return;
    }
    if( !out_visited.insert( pTerm ).second ) {
        return;
    }
    if( dynamic_cast<const vault::unify::VarTerm*>( pTerm ) ) {
        return;
    }
    vault::unify::AbstractTermIterator* pIt = pTerm->abstractTermIterator();
    if( pIt ) {
        while( pIt->isValid() ) {
            const vault::unify::TermTraversable* pChildTraversable = pIt->getTermTraversable();
            if( pChildTraversable ) {
                const vault::unify::AbstractTerm* pChildTerm =
                    dynamic_cast<const vault::unify::AbstractTerm*>( pChildTraversable );
                if( pChildTerm ) {
                    deleteScratchTermTree( pChildTerm, out_visited );
                }
            }
            pIt->next();
        }
        delete pIt;
    }
    delete pTerm;
}

} // anonymous namespace

/**
 * Factory class to factor a Goal from the syntax tree.
 *
 * This class traverses the XxxInput classes as generated by the parser
 * and generates appropriate AbstractTerm term trees that eventually are
 * used to create a set of goals representing the original goal input.
 * One main output goal is created from the main AbstractTerm tree as 
 * requested by the user. However, different additional trees may be
 * generated along the way.
 */
class AnyTermFactory
        : public boost::static_visitor<vault::unify::AbstractTerm*>
{
#if 0
    void storeTermDebugInfo( const AbstractTerm* pTerm,  )  {
        vault::unify::FileDebugInfo* pFDI = m_clauseContext.m_context.getFileDebugInfo();
        if( !pFDI ) return;
        if( pFDI ) {
            vault::unify::WorldPtr spWorld = m_clauseContext.m_context.getWorld();
            vault::unify::TermDebugInfo* pTDI = new vault::unify::TermDebugInfo(
                pTerm, pFDI, )
            spWorld.setTermDebugInfo( pTerm, )
        }
    }
#endif
public:
    /**
     * Create a new term factory within the given clause context. 
     */
    AnyTermFactory( 
        ClauseContext& clauseContext,
        std::list<vault::unify::AbstractTerm*>& out_lsTerms )
            : m_clauseContext( clauseContext ),
              m_lsTerms( out_lsTerms )
    {
    }

#if USE_NIL
    /**
     * We cannot factory anything of an unset variant.
     */
    vault::unify::AbstractTerm* operator()( const unifynil& ) const 
    {
        // do nothing.
        //BOOST_ASSERT(0);
        return 0;
    }
#endif


    vault::unify::AbstractTerm* operator()( const AnyTermInput& anyTermInput ) const 
    {
        return boost::apply_visitor( *this, anyTermInput.term );
    }

    vault::unify::AbstractTerm* operator()( const AnyStatementInput& anyStatementInput ) const 
    {
        return boost::apply_visitor( *this, anyStatementInput.statement );
    }

    vault::unify::AbstractTerm* operator()( const SingleGoalInput& singleGoalInput ) const 
    {
        vault::unify::AbstractTerm* pAbstractTerm = (*this)( singleGoalInput.rhs );

        if( singleGoalInput.first ) {
            vault::unify::ConsTerm* pConsTerm = dynamic_cast<vault::unify::ConsTerm*>( pAbstractTerm );
            if( pConsTerm ) {
                char op = singleGoalInput.first.get();
                if( '!'==op ) {
                    pConsTerm->setNegated( true );
                }
            } else {
                VAULT_UNIFY_DI( ALWAYS, "Unable to apply not operator: No consterm.\n" );
            }
        }

        return pAbstractTerm;
    }

    vault::unify::AbstractTerm* operator()( const PrefixTermInput& prefixTermInput ) const 
    {
        vault::unify::AbstractTerm* rhs;
        rhs = (*this)( prefixTermInput.rhs );

        // Do we have prefix operator at all?
        if( !prefixTermInput.first ) {
            // We don't, so just return right hand side.
            return rhs;
        }

        vault::unify::ConsTerm* termResult = NULL;

        // We have a prefix operator. Convert it to an internal call.
        char op = prefixTermInput.first.get();
        std::string atomName;
        switch( op ) {
        case '!': {
            atomName = "__builtin_not";
            break;
        default:
            break;
        }
        }

        // Create cons term, if not done yet.
        if( !termResult ) {
            termResult = new vault::unify::ConsTerm( atomName.c_str(), rhs );
            // storeTermDebugInfo( termResult );
        }

        return termResult;
    }

    /**
     * Fold a multiplicative ('*','/') or additive ('+','-') chain
     * left-to-right into nested `__builtin_arith(opAtom, lhs, rhs)`
     * ConsTerms -- e.g. `2 + 3 * 4` (parsed as additive(lhs=2,
     * rhsList=[{op='+',second=multiplicative(lhs=3,
     * rhsList=[{op='*',second=4}])}])) becomes
     * `__builtin_arith("+", 2, __builtin_arith("*", 3, 4))`. Both
     * m_ruleMultiplicative and m_ruleAdditive produce this same
     * ArithTermInput struct; precedence is already resolved by the
     * grammar's nesting (a multiplicative chain is always fully built
     * before it ever becomes one operand of an enclosing additive chain),
     * so this fold does not need to know which level it came from.
     *
     * Every ConsTerm allocated here (the op atom and the __builtin_arith
     * wrapper) becomes part of the enclosing clause/query's own term
     * tree exactly like any other ConsTerm this factory builds -- reachable
     * from the flat Goal term list Context::createGoal() assembles, and
     * freed by the same collectTermTree()-based sweep that already owns
     * every other parse-time term (World::~World() for a clause,
     * ~SolveJob() for a query). No new ownership mechanism is needed here.
     */
    vault::unify::AbstractTerm* operator()( const ArithTermInput& arithTermInput ) const
    {
        vault::unify::AbstractTerm* acc = (*this)( arithTermInput.lhs );

        std::vector<ArithTermRhsInput>::const_iterator it, itEnd = arithTermInput.rhsList.end();
        for( it = arithTermInput.rhsList.begin(); it != itEnd; ++it ) {
            vault::unify::AbstractTerm* rhsTerm = (*this)( it->second );
            std::string opStr( 1, it->op );
            vault::unify::ConsTerm* pOpAtom = new vault::unify::ConsTerm( opStr.c_str() );
            vault::unify::ConsTerm* pArith = new vault::unify::ConsTerm(
                "__builtin_arith", pOpAtom, acc, rhsTerm );
            acc = pArith;
        }

        return acc;
    }

    /**
     * Comparison level ('==','!=','<=','>=','<','>'): single-shot, unlike
     * the arithmetic chain above. No operator present -> just the lhs,
     * unchanged (the same "single operand" fast path InfixTermsInput uses
     * below). Otherwise builds `__builtin_compare(opAtom, lhs, rhs)`,
     * resolved by CompareBuiltinClause
     * (vault-unify-clause-builtin-arith.cpp). Ownership: same reasoning as
     * operator()(const ArithTermInput&) above -- ordinary parse-time
     * ConsTerms, no new ownership mechanism needed.
     */
    vault::unify::AbstractTerm* operator()( const CompareTermInput& compareTermInput ) const
    {
        vault::unify::AbstractTerm* lhs = (*this)( compareTermInput.lhs );

        if( !compareTermInput.rhs ) {
            return lhs;
        }
        const CompareTermRhsInput& cmpRhs = compareTermInput.rhs.get();
        vault::unify::AbstractTerm* rhs = (*this)( cmpRhs.second );

        vault::unify::ConsTerm* pOpAtom = new vault::unify::ConsTerm( cmpRhs.op.c_str() );
        vault::unify::ConsTerm* pCompare = new vault::unify::ConsTerm(
            "__builtin_compare", pOpAtom, lhs, rhs );

        return pCompare;
    }

    vault::unify::AbstractTerm* operator()( const InfixTermsInput& infixTermsInput ) const
    {
        vault::unify::AbstractTerm *lhs, *rhs, *out_pAbstractTerm = NULL;
        vault::unify::AbstractTerm *pPreGoal1 = NULL;
        vault::unify::VarTerm *pVarTerm1 = NULL;
        std::string strVarTerm1;

        // Get left hand side.
        lhs = (*this)( infixTermsInput.atilhs );

        // Special case: Just one operand.
        if( !infixTermsInput.rhs ) {
            out_pAbstractTerm = lhs;
            return out_pAbstractTerm;
        }
        const InfixTermRightHandSide& ifxrhs = infixTermsInput.rhs.get();

        char op = ifxrhs.first;
        rhs = (*this)( ifxrhs.second );

        WorldPtr spWorld( m_clauseContext.m_context.getWorld() );
        TermDebugInfo* pTermDebugInfo = spWorld->getTermDebugInfo( lhs );

        // Create the real atom from the infix operand.
        std::string atomName;
        switch( op ) {
        case '\0': {
            // Substitute deref here.
            //VAULT_UNIFY_DI( ALWAYS, "Creating deref member.\n" );
            atomName = "__builtin_member_deref";

            // =deref( lhs, rhs ) replaced by anon var __x
            // Pre-goal added
            // __builtin_member_deref( lhs, rhs, __x )
            pVarTerm1 = new vault::unify::VarTerm();
            strVarTerm1 = m_clauseContext.nextAnonVarName();
            pVarTerm1->setOriginalVarName( strVarTerm1 );
            m_clauseContext.m_mapSymbols[strVarTerm1] = pVarTerm1;

            pPreGoal1 = new vault::unify::ConsTerm( 
                atomName.c_str(), lhs, rhs, pVarTerm1 );

            if( pTermDebugInfo ) {
                spWorld->setTermDebugInfo( pPreGoal1, pTermDebugInfo);
            }

            // Add the new variable definition that resolves the member.
            m_lsTerms.push_back( pPreGoal1 );

            // Now create the variable reference in place of the 
            // original member deref
            out_pAbstractTerm = pVarTerm1;

            break;
        }
        case '=': {
            // Arithmetic-in-'=' desugar (ROADMAP Phase 2, SPEC.md section
            // 4): if either side is a `__builtin_arith` tree (built by
            // operator()(const ArithTermInput&) above), unify's plain
            // structural-equality semantics would never match it against
            // the evaluated result, so `=` means something different here:
            // evaluate the arithmetic side and unify the *result* with the
            // other side, via `__builtin_eval(arithSide, otherSide)`
            // (ArithEvalBuiltinClause, vault-unify-clause-builtin-arith.cpp).
            // A plain `=` between ordinary terms (neither side arithmetic)
            // is completely unchanged: still "unify".
            //
            // If BOTH sides happen to be arithmetic (e.g. `$x + 1 = $y + 2`),
            // the lhs wins arbitrarily (not a case any conformance test or
            // sample program exercises; not over-engineered here) -- the
            // rhs is then unified as a structural term against the
            // computed number, which simply will not unify.
            vault::unify::ConsTerm* pLhsCons = dynamic_cast<vault::unify::ConsTerm*>( lhs );
            vault::unify::ConsTerm* pRhsCons = dynamic_cast<vault::unify::ConsTerm*>( rhs );
            bool lhsIsArith = pLhsCons && 3==pLhsCons->getArity()
                && pLhsCons->getName().value() == "__builtin_arith";
            bool rhsIsArith = pRhsCons && 3==pRhsCons->getArity()
                && pRhsCons->getName().value() == "__builtin_arith";

            if( lhsIsArith || rhsIsArith ) {
                atomName = "__builtin_eval";
                if( lhsIsArith ) {
                    out_pAbstractTerm = new vault::unify::ConsTerm( atomName.c_str(), lhs, rhs );
                } else {
                    out_pAbstractTerm = new vault::unify::ConsTerm( atomName.c_str(), rhs, lhs );
                }
                if( pTermDebugInfo ) {
                    spWorld->setTermDebugInfo( out_pAbstractTerm, pTermDebugInfo );
                }
            } else {
                atomName = "unify";
            }
            break;
        }
        case '[':
            atomName = "__builtin_array_deref";
            break;
        default:
            atomName ="__builtin_undefined";
            break;
        }

        // Create cons term, if not done yet.
        if( !out_pAbstractTerm ) {
            out_pAbstractTerm = new vault::unify::ConsTerm( 
                atomName.c_str(), lhs, rhs );
            if( pTermDebugInfo ) {
                spWorld->setTermDebugInfo( out_pAbstractTerm, pTermDebugInfo );
            }        
        }

        return out_pAbstractTerm;
    }

    /**
     * `if( cond ) { body }` -- real if-then-else semantics (SPEC.md
     * sections 4, 9; ROADMAP Phase 2 "Cut"): like Prolog's
     * `( cond, !, body ; true )`. Desugars to a two-clause auxiliary
     * predicate appended to World's root ExecutionState:
     *
     *   __if_N( V1..Vk ) { clonedCond; __builtin_cut; clonedBody...; }
     *                                                      // then-branch,
     *                                                      // tried first
     *   __if_N( V1..Vk );                                 // fallback,
     *                                                      // tried only if
     *                                                      // cond fails
     *
     * plus a call site __if_N( origV1..origVk ) spliced into the
     * ENCLOSING goal chain in place of the `if` statement. V1..Vk are the
     * free variables of cond+body; origV1..origVk are the very same
     * VarTerm objects already in use by the enclosing clause/query
     * (m_clauseContext.m_mapSymbols), so the call site is simply part of
     * the enclosing term tree. Each synthesized clause instead gets its
     * OWN fresh variables (a fresh substitution built per clause, so the
     * two synthesized clauses do not even alias each other) via
     * cloneTermTree() -- see its declaration next to
     * collectTermTree()/deleteTermTree() in include/vault-unify.hpp. That
     * means neither synthesized clause shares a single term node with the
     * enclosing clause/query, killing the aliasing the previous
     * (broken -- see git history / ROADMAP) desugaring relied on.
     *
     * The `__builtin_cut` inserted right after clonedCond (see below) is
     * the reserved term SolveJob::performSlice() (vault-unify-solvejob.cpp)
     * recognizes directly -- once cond succeeds for the first time, it
     * commits: no further clause is tried for the __if_N(...) call site
     * (so the fallback below never runs once cond has succeeded at least
     * once) and cond itself does not backtrack for a second solution
     * either. If cond fails outright, the then-branch clause never reaches
     * the cut at all, and the fallback (always succeeds, empty body) runs
     * normally -- exactly if-then-else. This used to be a soft-if
     * (`( cond, body ; true )`, no commit, SPEC.md section 9 QUIRK) before
     * cut existed; see test/conformance/if-statement.ufy, whose first
     * query used to print the line after the `if` twice for exactly that
     * reason and now prints it once.
     */
    vault::unify::AbstractTerm* operator()( const IfStatementInput& ifStatementInput ) const
    {
        // a. Build cond and body as term trees using the ENCLOSING
        // clause/query's own variable scope (m_clauseContext), exactly
        // like any other goal built in this context -- this is what lets
        // us later tell which VarTerms are free (shared with the rest of
        // the enclosing clause/query) instead of guessing from the AST.
        // Each gets its own local pre-goal list (mirroring how
        // Context::createGoal() always hands a fresh AnyTermFactory a
        // fresh output list bound to the SAME ClauseContext), so any
        // pre-goals from a nested desugaring (e.g. '->') land next to the
        // term that needs them, not in the enclosing goal.
        std::list<vault::unify::AbstractTerm*> lsCondPreGoals;
        AnyTermFactory condFactory( m_clauseContext, lsCondPreGoals );
        vault::unify::AbstractTerm* pCondTerm = condFactory( ifStatementInput.lhs );

        std::list<vault::unify::AbstractTerm*> lsBodyTerms;
        (void) m_clauseContext.m_context.createGoal(
            m_clauseContext, ifStatementInput.rhs, lsBodyTerms );

        // All roots that make up the synthesized rule's body, in the
        // order they must run in: cond's own pre-goals, then cond itself,
        // then the body's statements (already pre-goal-inclusive, since
        // createGoal() interleaves them itself).
        std::vector<const vault::unify::AbstractTerm*> auxRuleRoots;
        auxRuleRoots.reserve( lsCondPreGoals.size() + 1 + lsBodyTerms.size() );
        {
            std::list<vault::unify::AbstractTerm*>::const_iterator it, itEnd;
            for( it = lsCondPreGoals.begin(), itEnd = lsCondPreGoals.end(); it != itEnd; ++it ) {
                auxRuleRoots.push_back( *it );
            }
        }
        auxRuleRoots.push_back( pCondTerm );
        {
            std::list<vault::unify::AbstractTerm*>::const_iterator it, itEnd;
            for( it = lsBodyTerms.begin(), itEnd = lsBodyTerms.end(); it != itEnd; ++it ) {
                auxRuleRoots.push_back( *it );
            }
        }

        // b. Collect the distinct free VarTerms across cond+body.
        std::vector<vault::unify::VarTerm*> freeVars;
        {
            std::set<const vault::unify::AbstractTerm*> visited;
            std::vector<const vault::unify::AbstractTerm*>::const_iterator it, itEnd = auxRuleRoots.end();
            for( it = auxRuleRoots.begin(); it != itEnd; ++it ) {
                collectVarTermsOrdered( *it, visited, freeVars );
            }
        }
        const int nVars = (int) freeVars.size();

        // c. Unique auxiliary predicate name (existing anon-clause
        // counter machinery, e.g. "__if__3").
        vault::unify::Atom auxAtom( m_clauseContext.nextAnonClauseName( "if" ) );

        WorldPtr spWorld( m_clauseContext.m_context.getWorld() );

        // d./e. Give each synthesized clause its OWN fresh substitution
        // (and thus its own head variables) -- the Rule and the Fact
        // clause below do not share a single VarTerm, let alone anything
        // with the enclosing clause/query.
        std::map<const vault::unify::VarTerm*, vault::unify::VarTerm*> subMapRule;
        vault::unify::AbstractTerm** ppHeadArgsRule = nVars ? new vault::unify::AbstractTerm*[nVars] : NULL;
        for( int i = 0; i < nVars; ++i ) {
            vault::unify::VarTerm* pFreshVar = new vault::unify::VarTerm();
            pFreshVar->setOriginalVarName( freeVars[i]->getOriginalVarName() );
            subMapRule[freeVars[i]] = pFreshVar;
            ppHeadArgsRule[i] = pFreshVar;
        }
        vault::unify::ConsTerm* pHeadRule = new vault::unify::ConsTerm( auxAtom, nVars, ppHeadArgsRule );
        // ConsTerm's ctor (see AnyTermFactory::operator()(ConsTermInput))
        // only copies the pointer VALUES out of ppHeadArgsRule into its own
        // m_vecTerms; it never takes ownership of the buffer itself.
        delete[] ppHeadArgsRule;

        std::map<const vault::unify::VarTerm*, vault::unify::VarTerm*> subMapFact;
        vault::unify::AbstractTerm** ppHeadArgsFact = nVars ? new vault::unify::AbstractTerm*[nVars] : NULL;
        for( int i = 0; i < nVars; ++i ) {
            vault::unify::VarTerm* pFreshVar = new vault::unify::VarTerm();
            pFreshVar->setOriginalVarName( freeVars[i]->getOriginalVarName() );
            subMapFact[freeVars[i]] = pFreshVar;
            ppHeadArgsFact[i] = pFreshVar;
        }
        vault::unify::ConsTerm* pHeadFact = new vault::unify::ConsTerm( auxAtom, nVars, ppHeadArgsFact );
        delete[] ppHeadArgsFact;

        // Clone cond's pre-goals + cond + body into the Rule clause's
        // body, via subMapRule -- shares nothing with the scratch trees
        // built in step (a), nor with the Fact clause's own clone below.
        // Right after cond's own clone, splice in a fresh `__builtin_cut`
        // term (ROADMAP Phase 2 "Cut", see the doc comment above): it
        // needs no cloning/substitution (it has no VarTerm of its own),
        // and it is a genuinely new, parse-time-allocated term reachable
        // from pRuleGoal's Goal::m_listAbstractTerms exactly like every
        // other term of this synthesized clause below -- freed by the
        // same collectTermTree()-based sweep that already owns the rest
        // of it (World::~World()), so no new ownership tracking is needed.
        std::list<const vault::unify::AbstractTerm*> lsClonedRuleBody;
        {
            std::vector<const vault::unify::AbstractTerm*>::const_iterator it, itEnd = auxRuleRoots.end();
            for( it = auxRuleRoots.begin(); it != itEnd; ++it ) {
                lsClonedRuleBody.push_back( vault::unify::cloneTermTree( *it, subMapRule ) );
                if( *it == pCondTerm ) {
                    lsClonedRuleBody.push_back( new vault::unify::ConsTerm( "__builtin_cut" ) );
                }
            }
        }
        vault::unify::Goal* pRuleGoal = new vault::unify::Goal(
            lsClonedRuleBody.begin(), lsClonedRuleBody.end() );

        Clause* pRuleClause = new vault::unify::StandardClause( pHeadRule, pRuleGoal );
        Clause* pFactClause = new vault::unify::StandardClause( pHeadFact, NULL );

        // Definition order: then-branch first, fallback second (so a
        // depth-first, all-solutions search tries "cond succeeded" before
        // "cond was skipped" -- see SPEC.md section 5 and the caveat
        // above this function).
        spWorld->getRootState()->appendClause( spWorld, pRuleClause );
        spWorld->getRootState()->appendClause( spWorld, pFactClause );
        VAULT_UNIFY_DI( ALWAYS, "Added clause '%s'.\n", pRuleClause->toString().c_str() );
        VAULT_UNIFY_DI( ALWAYS, "Added clause '%s'.\n", pFactClause->toString().c_str() );

        // The scratch cond/body trees built in step (a) (using the
        // enclosing context) have now been fully cloned into the
        // synthesized Rule clause; free their structural (non-VarTerm)
        // nodes. The VarTerms among them are NOT scratch -- they are
        // exactly `freeVars`, which the call site below reuses directly,
        // so they remain reachable from (and owned along with) the
        // enclosing clause/query's own term tree.
        {
            std::set<const vault::unify::AbstractTerm*> visited;
            std::vector<const vault::unify::AbstractTerm*>::const_iterator it, itEnd = auxRuleRoots.end();
            for( it = auxRuleRoots.begin(); it != itEnd; ++it ) {
                deleteScratchTermTree( *it, visited );
            }
        }

        // f. The call site: __if_N( origV1..origVk ), built from the
        // ORIGINAL enclosing VarTerms. This is the if-statement's own
        // contribution to the enclosing goal chain.
        //
        // g. K==0 (no free variables, as in e.g. `if( flag( on ) ) {...}`
        // with no variables anywhere in cond/body) is handled the same
        // way arity-0 calls always are in this parser (see
        // operator()(ConsTermInput) above): nVars==0, ppCallArgs==NULL,
        // ConsTerm's vector is constructed from an empty [ppTerms,
        // ppTerms+0) range -- nothing special required.
        vault::unify::AbstractTerm** ppCallArgs = nVars ? new vault::unify::AbstractTerm*[nVars] : NULL;
        for( int i = 0; i < nVars; ++i ) {
            ppCallArgs[i] = freeVars[i];
        }
        vault::unify::ConsTerm* pCallTerm = new vault::unify::ConsTerm( auxAtom, nVars, ppCallArgs );
        delete[] ppCallArgs;

        // h. Deliberately not registering any TermDebugInfo for the
        // synthesized clauses/call site -- the old code didn't either,
        // and doing so here would mean sharing one TermDebugInfo across
        // several term keys again (World::~World() already has to guard
        // against exactly that for the '->' desugaring).
        return pCallTerm;
    }


    vault::unify::AbstractTerm* operator()( const ConsTermInput& consTermInput ) const 
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        std::string consTermInputName = consTermInput.atom.name;

        // ROADMAP Phase 2 (Cut): the bareword goal `cut` (zero arguments)
        // is a reserved word -- mirroring how `query` is reserved for a
        // zero-argument top-level head (SPEC.md) -- for the committed-
        // choice construct SolveJob::performSlice() (vault-unify-solvejob.cpp)
        // recognizes directly by this exact internal name; cut is NEVER a
        // registered Clause/builtin (it needs access to the SolveContext
        // stack itself, which no Clause ever gets). Renamed here, at
        // term-construction time, so every position a bareword ConsTerm
        // can occur in -- a goal statement, a clause head, or a plain
        // argument -- is covered by one change. `cut(...)` with one or
        // more arguments is completely unaffected: a normal clause/call
        // named "cut", exactly like `query(a)` stays a normal clause head
        // once it takes an argument.
        if( consTermInputName=="cut" && consTermInput.values.empty() ) {
            consTermInputName = "__builtin_cut";
        }

        // Atom used, if at all, only to copy-construct ConsTerm::m_name
        // (which stores it BY VALUE) below -- a stack instance avoids
        // orphaning a heap Atom on every single call (both the VarTerm
        // branch, which never even looks at it, and the ConsTerm branch,
        // whose constructor only ever copies from it).
        vault::unify::Atom atom( consTermInputName );

        // Is it a consterm or a varterm?
        char ch = consTermInputName[0];
        if( '$' == ch ) {
            // VarTerm.
            vault::unify::VarTerm* pVarTerm = NULL;
            std::map<std::string,vault::unify::VarTerm*>::iterator itSym =
                m_clauseContext.m_mapSymbols.find( consTermInputName );
            if( itSym==m_clauseContext.m_mapSymbols.end() ) {
                // Does not exist, create.
                pVarTerm = new vault::unify::VarTerm();
                pVarTerm->setOriginalVarName( consTermInputName );
                m_clauseContext.m_mapSymbols[consTermInputName] = pVarTerm;
            } else {
                pVarTerm = itSym->second;
            }
            out_pAbstractTerm = pVarTerm;
        } else {
            vault::unify::AbstractTerm** ppTerms;
            int nTerms;
            if( consTermInput.values.empty() ) {
                nTerms = 0;
                ppTerms = NULL;
            } else {
                nTerms = consTermInput.values.size();
                ppTerms = new vault::unify::AbstractTerm*[nTerms];
                for( int i=0; i<nTerms; ++i ) {
                    vault::unify::AbstractTerm* pAbstractTerm = NULL;
                    pAbstractTerm = (*this)( consTermInput.values[i] );
                    ppTerms[i] = pAbstractTerm;
                }
            }
            vault::unify::ConsTerm* pConsTerm = new vault::unify::ConsTerm(
                atom, nTerms, ppTerms );
            // ConsTerm's ctor copies the pointer VALUES from ppTerms into
            // its own m_vecTerms (constructed from the [ppTerms,ppTerms+n)
            // range) -- it does not take ownership of the ppTerms buffer
            // itself, only of the children it points to. Free the
            // now-redundant transient buffer (safe/no-op when NULL).
            delete[] ppTerms;
            out_pAbstractTerm = pConsTerm;
        }

        // Add debug info.
        if( out_pAbstractTerm ) {
            const vault::unify::FileDebugInfo* pFileDebugInfo =
                m_clauseContext.m_context.getFileDebugInfo();
            vault::unify::TermDebugInfo* pTermDebugInfo =
                new vault::unify::TermDebugInfo( out_pAbstractTerm, pFileDebugInfo, 
                    consTermInput.atom.line );
            m_clauseContext.m_context.getWorld()->setTermDebugInfo(
                out_pAbstractTerm, pTermDebugInfo );
        }

        return out_pAbstractTerm;
    }


    vault::unify::AbstractTerm* operator()( const ArrayTermInput& arrayTermInput ) const
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        int nTerms;
        const vault::unify::Atom** ppAtoms;
        vault::unify::AbstractTerm** ppTerms;
       

        if( arrayTermInput.members.empty() ) {
            nTerms = 0;
            ppAtoms = NULL;
            ppTerms = NULL;
        } else {
            nTerms = arrayTermInput.members.size();
            ppAtoms = new const vault::unify::Atom*[nTerms];
            ppTerms = new vault::unify::AbstractTerm*[nTerms];
            for( int i=0; i<nTerms; ++i ) {
                char s[20];
                snprintf( s, 20, "%d", i );
                ppAtoms[i] = new vault::unify::Atom( s );
                vault::unify::AbstractTerm* pAbstractTerm = NULL;
                pAbstractTerm = (*this)( arrayTermInput.members[i] );
                ppTerms[i] = pAbstractTerm;
            }
        }

        vault::unify::MapTerm* pMapTerm = new vault::unify::MapTerm(
            ppAtoms, ppTerms, nTerms );
        // MapTerm's ctor copies the *pointer values* out of ppAtoms/ppTerms
        // into its own m_mapContents; it never takes ownership of the two
        // transient buffers themselves (only of the Atoms/terms they
        // point to). Free the now-redundant buffers (safe/no-op when NULL).
        delete[] ppAtoms;
        delete[] ppTerms;
        out_pAbstractTerm = pMapTerm;

        return out_pAbstractTerm;
    }

    vault::unify::AbstractTerm* operator()( const MapTermInput& mapTermInput ) const
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        int nTerms;
        const vault::unify::Atom** ppAtoms;
        vault::unify::AbstractTerm** ppTerms;

        if( mapTermInput.pairs.empty() ) {
            nTerms = 0;
            ppAtoms = NULL;
            ppTerms = NULL;
        } else {
            nTerms = mapTermInput.pairs.size();
            ppAtoms = new const vault::unify::Atom*[nTerms];
            ppTerms = new vault::unify::AbstractTerm*[nTerms];
            for( int i=0; i<nTerms; ++i ) {
                ppAtoms[i] = new vault::unify::Atom( mapTermInput.pairs[i].pairKey.name );
                vault::unify::AbstractTerm* pAbstractTerm = NULL;
                pAbstractTerm = (*this)( mapTermInput.pairs[i].pairValue );
                ppTerms[i] = pAbstractTerm;
            }
        }

        vault::unify::MapTerm* pMapTerm = new vault::unify::MapTerm(
            ppAtoms, ppTerms, nTerms );
        // See ArrayTermInput overload above: MapTerm only takes ownership
        // of the Atoms/terms these buffers point to, not of the buffers.
        delete[] ppAtoms;
        delete[] ppTerms;
        out_pAbstractTerm = pMapTerm;

        return out_pAbstractTerm;
    }

private:
    /**
     * The actual context we are running in. This defines a current set of
     * variable symbol definitions as required for interpreting the AST.
     */
    ClauseContext& m_clauseContext;

    /**
     * The list of goals we create alongside. The main goal will not
     * be created by this class. It shall be pushed back by the caller.
     */
    std::list<vault::unify::AbstractTerm*>& m_lsTerms;
};

}
}
}


/**
 * Factor a goal from a goal input term.
 * 
 * @param clauseContext
 *     The context of the current clause. This context e.g. contains the
 *     variable mappings as valid within the current clause.
 * @param out_lsGoals
 *     A list of goals as created by this input goal. Several goals
 *     maybe created due to conversion of builtin syntax-terms to
 *     auxialiare goals.
 */
int vault::unify::PrologParser::Context::createGoal(
        vault::unify::PrologParser::ClauseContext& clauseContext,
        const vault::unify::PrologParser::GoalInput& goalInput,
        std::list<vault::unify::AbstractTerm*>& out_lsTerms
        )
{
    std::list<vault::unify::AbstractTerm*> localTermList;
    std::vector<vault::unify::PrologParser::AnyStatementInput>::const_iterator
        itBegin = goalInput.consTerms.begin(),
        itEnd = goalInput.consTerms.end();

    AnyTermFactory anyTermFactory( clauseContext, out_lsTerms );

    for( ; itBegin != itEnd; ++itBegin ) {
        vault::unify::AbstractTerm* pAbstractTerm = NULL;

        pAbstractTerm = anyTermFactory( *itBegin );
        // Make this a AST parsing time assumption.
        //localTermList.push_back( pAbstractTerm );
        out_lsTerms.push_back( pAbstractTerm );
    }
    // Do not create a goal at this point. Instead, return the term list.
    // vault::unify::Goal* pGoal = new vault::unify::Goal(
    //     consTermList.begin(), consTermList.end() );
    // out_lsGoals.push_back( pGoal );
    return 0;
}


int vault::unify::PrologParser::Context::createClause(
        vault::unify::PrologParser::ClauseContext& clauseContext,
        const vault::unify::PrologParser::ClauseInput& clauseInput,
        vault::unify::Clause*& out_pClause )
{
    // Left hand side.
    vault::unify::AbstractTerm* pAbstractTerm = NULL;
    {
        std::list<vault::unify::AbstractTerm*> lsClauseTerm;
        AnyTermFactory anyTermFactory( clauseContext, lsClauseTerm );
        pAbstractTerm = anyTermFactory( clauseInput.leftHandTerm );
        if( !lsClauseTerm.empty() ) {
            // TXWTODO: Error handling?
            VAULT_UNIFY_DI( ALWAYS, "Clause lhs has more then one term.\n" );
            return -1;
        }
    }
    // Right hand side.
    vault::unify::Goal* pGoal = NULL;
    {
        // The terms of the goal, which is our right hand side.
        std::list<vault::unify::AbstractTerm*> lsGoalTerms;
        // The rhs goal.
        if( !clauseInput.rightHandGoal.consTerms.empty() ) { 
            (void) createGoal( clauseContext, clauseInput.rightHandGoal, lsGoalTerms );
            pGoal = new vault::unify::Goal(
                lsGoalTerms.begin(), lsGoalTerms.end() );
        }
    }
    {
        // Make up clause from lhs and rhs.
        vault::unify::Clause* pClause = new vault::unify::StandardClause(
            dynamic_cast<vault::unify::ConsTerm*>( pAbstractTerm ), pGoal );
        out_pClause = pClause;
    }
    return 0;
}


