

#include <stdio.h>
#include <stdlib.h>

/*
 * Workaround for a but in boost 1.58: It does not support
 * empty structs in BOOST_FUSION_ADOPT_STRUCT
 */
#undef BOOST_PP_VARIADICS
#define BOOST_PP_VARIADICS 0

#include <vault-unify-parser.hpp>

#include <vault-unify-clause-standard.hpp>

#include <vault-unify-debug.hpp>

namespace vault {
namespace unify {
namespace PrologParser {

int ClauseContext::m_anonClauseIndex;

/**
 * Factory class to factor a Goal from the syntax tree.
 *
 * This class traverses the XxxInput classes as generated by the parser
 * and generates appropriate AbstractTerm term trees that eventually are
 * used to create a set of goals representing the original goal input.
 * One main output goal is created from the main AbstractTerm tree as 
 * requested by the user. However, different additional trees may be
 * generated along the way.
 */
class AnyTermFactory
        : public boost::static_visitor<vault::unify::AbstractTerm*>
{
#if 0
    void storeTermDebugInfo( const AbstractTerm* pTerm,  )  {
        vault::unify::FileDebugInfo* pFDI = m_clauseContext.m_context.getFileDebugInfo();
        if( !pFDI ) return;
        if( pFDI ) {
            vault::unify::WorldPtr spWorld = m_clauseContext.m_context.getWorld();
            vault::unify::TermDebugInfo* pTDI = new vault::unify::TermDebugInfo(
                pTerm, pFDI, )
            spWorld.setTermDebugInfo( pTerm, )
        }
    }
#endif
public:
    /**
     * Create a new term factory within the given clause context. 
     */
    AnyTermFactory( 
        ClauseContext& clauseContext,
        std::list<vault::unify::AbstractTerm*>& out_lsTerms )
            : m_clauseContext( clauseContext ),
              m_lsTerms( out_lsTerms )
    {
    }

#if USE_NIL
    /**
     * We cannot factory anything of an unset variant.
     */
    vault::unify::AbstractTerm* operator()( const unifynil& ) const 
    {
        // do nothing.
        //BOOST_ASSERT(0);
        return 0;
    }
#endif


    vault::unify::AbstractTerm* operator()( const AnyTermInput& anyTermInput ) const 
    {
        return boost::apply_visitor( *this, anyTermInput.term );
    }

    vault::unify::AbstractTerm* operator()( const AnyStatementInput& anyStatementInput ) const 
    {
        return boost::apply_visitor( *this, anyStatementInput.statement );
    }

    vault::unify::AbstractTerm* operator()( const SingleGoalInput& singleGoalInput ) const 
    {
        vault::unify::AbstractTerm* pAbstractTerm = (*this)( singleGoalInput.rhs );

        if( singleGoalInput.first ) {
            vault::unify::ConsTerm* pConsTerm = dynamic_cast<vault::unify::ConsTerm*>( pAbstractTerm );
            if( pConsTerm ) {
                char op = singleGoalInput.first.get();
                if( '!'==op ) {
                    pConsTerm->setNegated( true );
                }
            } else {
                VAULT_UNIFY_DI( ALWAYS, "Unable to apply not operator: No consterm.\n" );
            }
        }

        return pAbstractTerm;
    }

    vault::unify::AbstractTerm* operator()( const PrefixTermInput& prefixTermInput ) const 
    {
        vault::unify::AbstractTerm* rhs;
        rhs = (*this)( prefixTermInput.rhs );

        // Do we have prefix operator at all?
        if( !prefixTermInput.first ) {
            // We don't, so just return right hand side.
            return rhs;
        }

        vault::unify::ConsTerm* termResult = NULL;

        // We have a prefix operator. Convert it to an internal call.
        char op = prefixTermInput.first.get();
        std::string atomName;
        switch( op ) {
        case '!': {
            atomName = "__builtin_not";
            break;
        default:
            break;
        }
        }

        // Create cons term, if not done yet.
        if( !termResult ) {
            termResult = new vault::unify::ConsTerm( atomName.c_str(), rhs );
            // storeTermDebugInfo( termResult );
        }

        return termResult;
    }

    vault::unify::AbstractTerm* operator()( const InfixTermsInput& infixTermsInput ) const 
    {
        vault::unify::AbstractTerm *lhs, *rhs, *out_pAbstractTerm = NULL;
        vault::unify::AbstractTerm *pPreGoal1 = NULL;
        vault::unify::VarTerm *pVarTerm1 = NULL;
        std::string strVarTerm1;

        // Get left hand side.
        lhs = (*this)( infixTermsInput.atilhs );

        // Special case: Just one operand.
        if( !infixTermsInput.rhs ) {
            out_pAbstractTerm = lhs;
            return out_pAbstractTerm;
        }
        const InfixTermRightHandSide& ifxrhs = infixTermsInput.rhs.get();

        char op = ifxrhs.first;
        rhs = (*this)( ifxrhs.second );

        WorldPtr spWorld( m_clauseContext.m_context.getWorld() );
        TermDebugInfo* pTermDebugInfo = spWorld->getTermDebugInfo( lhs );

        // Create the real atom from the infix operand.
        std::string atomName;
        switch( op ) {
        case '\0': {
            // Substitute deref here.
            //VAULT_UNIFY_DI( ALWAYS, "Creating deref member.\n" );
            atomName = "__builtin_member_deref";

            // =deref( lhs, rhs ) replaced by anon var __x
            // Pre-goal added
            // __builtin_member_deref( lhs, rhs, __x )
            pVarTerm1 = new vault::unify::VarTerm();
            strVarTerm1 = m_clauseContext.nextAnonVarName();
            pVarTerm1->setOriginalVarName( strVarTerm1 );
            m_clauseContext.m_mapSymbols[strVarTerm1] = pVarTerm1;

            pPreGoal1 = new vault::unify::ConsTerm( 
                atomName.c_str(), lhs, rhs, pVarTerm1 );

            if( pTermDebugInfo ) {
                spWorld->setTermDebugInfo( pPreGoal1, pTermDebugInfo);
            }

            // Add the new variable definition that resolves the member.
            m_lsTerms.push_back( pPreGoal1 );

            // Now create the variable reference in place of the 
            // original member deref
            out_pAbstractTerm = pVarTerm1;

            break;
        }
        case '=':
            atomName = "unify";
            break;
        case '[':
            atomName = "__builtin_array_deref";
            break;
        default:
            atomName ="__builtin_undefined";
            break;
        }

        // Create cons term, if not done yet.
        if( !out_pAbstractTerm ) {
            out_pAbstractTerm = new vault::unify::ConsTerm( 
                atomName.c_str(), lhs, rhs );
            if( pTermDebugInfo ) {
                spWorld->setTermDebugInfo( out_pAbstractTerm, pTermDebugInfo );
            }        
        }

        return out_pAbstractTerm;
    }

    vault::unify::AbstractTerm* operator()( const IfStatementInput& ifStatementInput ) const 
    {
        vault::unify::AbstractTerm /* *lhs, *rhs, */ *pAbstractTerm = NULL;

        /*
         * If statement works like this: We declare a new anon clause.
         * Declare new clase 
         * userclause: pregoals, $cond, $goal, postgoals, cut
         * userclause: pregoals, postgoals
         */
        // Define new clause
        std::string strClauseName( m_clauseContext.nextAnonClauseName( "if" ) );
        ConsTermInput cti;
        cti.atom = AtomInput( strClauseName, 1 );
        std::string strVarName = m_clauseContext.nextAnonVarName();
        cti.values.insert( cti.values.begin(), AnyTermInput( ConsTermInput( AtomInput( strVarName, 1 ) ) ) );
        ClauseInput ci;
        ci.leftHandTerm = cti;
        ci.rightHandGoal = ifStatementInput.rhs;
        // And prepend the variable 
        ci.rightHandGoal.consTerms.insert( ci.rightHandGoal.consTerms.begin(),
            AnyStatementInput(
                SingleGoalInput( 
                    InfixTermsInput(
                        AnyTermInput( 
                            ConsTermInput( 
                                AtomInput( strVarName, 1 )
                                )
                            )
                        )
                    )
                )
            );
        // Now create the new clause.
        Clause* pClause = NULL;
        (void) m_clauseContext.m_context.createClause(
            m_clauseContext, ci, pClause );
        WorldPtr spWorld( m_clauseContext.m_context.getWorld() );
        spWorld->getRootState()->appendClause( spWorld, pClause );
        VAULT_UNIFY_DI( ALWAYS, "Added clause '%s'.\n", 
            pClause->toString().c_str() );
        // We evaluate to calling the clause.
        pAbstractTerm = (*this)( cti );
        return pAbstractTerm;
    }


    vault::unify::AbstractTerm* operator()( const ConsTermInput& consTermInput ) const 
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        std::string consTermInputName = consTermInput.atom.name;
        vault::unify::Atom* pAtom = new vault::unify::Atom( consTermInputName );

        // Is it a consterm or a varterm?
        char ch = consTermInputName[0];
        if( '$' == ch ) {
            // VarTerm.
            vault::unify::VarTerm* pVarTerm = NULL;
            std::map<std::string,vault::unify::VarTerm*>::iterator itSym =
                m_clauseContext.m_mapSymbols.find( consTermInputName );
            if( itSym==m_clauseContext.m_mapSymbols.end() ) {
                // Does not exist, create.
                pVarTerm = new vault::unify::VarTerm();
                pVarTerm->setOriginalVarName( consTermInputName );
                m_clauseContext.m_mapSymbols[consTermInputName] = pVarTerm; 
            } else {
                pVarTerm = itSym->second;
            }
            out_pAbstractTerm = pVarTerm;
        } else {
            vault::unify::AbstractTerm** ppTerms;
            int nTerms;
            if( consTermInput.values.empty() ) {
                nTerms = 0;
                ppTerms = NULL;
            } else {
                nTerms = consTermInput.values.size();
                ppTerms = new vault::unify::AbstractTerm*[nTerms];
                for( int i=0; i<nTerms; ++i ) {
                    vault::unify::AbstractTerm* pAbstractTerm = NULL;
                    pAbstractTerm = (*this)( consTermInput.values[i] );
                    ppTerms[i] = pAbstractTerm;
                }
            }
            vault::unify::ConsTerm* pConsTerm = new vault::unify::ConsTerm(
                *pAtom, nTerms, ppTerms );
            out_pAbstractTerm = pConsTerm;
        }

        // Add debug info.
        if( out_pAbstractTerm ) {
            const vault::unify::FileDebugInfo* pFileDebugInfo =
                m_clauseContext.m_context.getFileDebugInfo();
            vault::unify::TermDebugInfo* pTermDebugInfo =
                new vault::unify::TermDebugInfo( out_pAbstractTerm, pFileDebugInfo, 
                    consTermInput.atom.line );
            m_clauseContext.m_context.getWorld()->setTermDebugInfo(
                out_pAbstractTerm, pTermDebugInfo );
        }

        return out_pAbstractTerm;
    }


    vault::unify::AbstractTerm* operator()( const ArrayTermInput& arrayTermInput ) const
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        int nTerms;
        const vault::unify::Atom** ppAtoms;
        vault::unify::AbstractTerm** ppTerms;
       

        if( arrayTermInput.members.empty() ) {
            nTerms = 0;
            ppAtoms = NULL;
            ppTerms = NULL;
        } else {
            nTerms = arrayTermInput.members.size();
            ppAtoms = new const vault::unify::Atom*[nTerms];
            ppTerms = new vault::unify::AbstractTerm*[nTerms];
            for( int i=0; i<nTerms; ++i ) {
                char s[20];
                snprintf( s, 20, "%d", i );
                ppAtoms[i] = new vault::unify::Atom( s );
                vault::unify::AbstractTerm* pAbstractTerm = NULL;
                pAbstractTerm = (*this)( arrayTermInput.members[i] );
                ppTerms[i] = pAbstractTerm;
            }
        }

        vault::unify::MapTerm* pMapTerm = new vault::unify::MapTerm(
            ppAtoms, ppTerms, nTerms );
        out_pAbstractTerm = pMapTerm;

        return out_pAbstractTerm;
    }

    vault::unify::AbstractTerm* operator()( const MapTermInput& mapTermInput ) const 
    {
        vault::unify::AbstractTerm* out_pAbstractTerm = NULL;
        int nTerms;
        const vault::unify::Atom** ppAtoms;
        vault::unify::AbstractTerm** ppTerms;

        if( mapTermInput.pairs.empty() ) {
            nTerms = 0;
            ppAtoms = NULL;
            ppTerms = NULL;
        } else {
            nTerms = mapTermInput.pairs.size();
            ppAtoms = new const vault::unify::Atom*[nTerms];
            ppTerms = new vault::unify::AbstractTerm*[nTerms];
            for( int i=0; i<nTerms; ++i ) {
                ppAtoms[i] = new vault::unify::Atom( mapTermInput.pairs[i].pairKey.name );
                vault::unify::AbstractTerm* pAbstractTerm = NULL;
                pAbstractTerm = (*this)( mapTermInput.pairs[i].pairValue );
                ppTerms[i] = pAbstractTerm;
            }
        }

        vault::unify::MapTerm* pMapTerm = new vault::unify::MapTerm(
            ppAtoms, ppTerms, nTerms );
        out_pAbstractTerm = pMapTerm;

        return out_pAbstractTerm;
    }

private:
    /**
     * The actual context we are running in. This defines a current set of
     * variable symbol definitions as required for interpreting the AST.
     */
    ClauseContext& m_clauseContext;

    /**
     * The list of goals we create alongside. The main goal will not
     * be created by this class. It shall be pushed back by the caller.
     */
    std::list<vault::unify::AbstractTerm*>& m_lsTerms;
};

}
}
}


/**
 * Factor a goal from a goal input term.
 * 
 * @param clauseContext
 *     The context of the current clause. This context e.g. contains the
 *     variable mappings as valid within the current clause.
 * @param out_lsGoals
 *     A list of goals as created by this input goal. Several goals
 *     maybe created due to conversion of builtin syntax-terms to
 *     auxialiare goals.
 */
int vault::unify::PrologParser::Context::createGoal(
        vault::unify::PrologParser::ClauseContext& clauseContext,
        const vault::unify::PrologParser::GoalInput& goalInput,
        std::list<vault::unify::AbstractTerm*>& out_lsTerms
        )
{
    std::list<vault::unify::AbstractTerm*> localTermList;
    std::vector<vault::unify::PrologParser::AnyStatementInput>::const_iterator
        itBegin = goalInput.consTerms.begin(),
        itEnd = goalInput.consTerms.end();

    AnyTermFactory anyTermFactory( clauseContext, out_lsTerms );

    for( ; itBegin != itEnd; ++itBegin ) {
        vault::unify::AbstractTerm* pAbstractTerm = NULL;

        pAbstractTerm = anyTermFactory( *itBegin );
        // Make this a AST parsing time assumption.
        //localTermList.push_back( pAbstractTerm );
        out_lsTerms.push_back( pAbstractTerm );
    }
    // Do not create a goal at this point. Instead, return the term list.
    // vault::unify::Goal* pGoal = new vault::unify::Goal(
    //     consTermList.begin(), consTermList.end() );
    // out_lsGoals.push_back( pGoal );
    return 0;
}


int vault::unify::PrologParser::Context::createClause(
        vault::unify::PrologParser::ClauseContext& clauseContext,
        const vault::unify::PrologParser::ClauseInput& clauseInput,
        vault::unify::Clause*& out_pClause )
{
    // Left hand side.
    vault::unify::AbstractTerm* pAbstractTerm = NULL;
    {
        std::list<vault::unify::AbstractTerm*> lsClauseTerm;
        AnyTermFactory anyTermFactory( clauseContext, lsClauseTerm );
        pAbstractTerm = anyTermFactory( clauseInput.leftHandTerm );
        if( !lsClauseTerm.empty() ) {
            // TXWTODO: Error handling?
            VAULT_UNIFY_DI( ALWAYS, "Clause lhs has more then one term.\n" );
            return -1;
        }
    }
    // Right hand side.
    vault::unify::Goal* pGoal = NULL;
    {
        // The terms of the goal, which is our right hand side.
        std::list<vault::unify::AbstractTerm*> lsGoalTerms;
        // The rhs goal.
        if( !clauseInput.rightHandGoal.consTerms.empty() ) { 
            (void) createGoal( clauseContext, clauseInput.rightHandGoal, lsGoalTerms );
            pGoal = new vault::unify::Goal(
                lsGoalTerms.begin(), lsGoalTerms.end() );
        }
    }
    {
        // Make up clause from lhs and rhs.
        vault::unify::Clause* pClause = new vault::unify::StandardClause(
            dynamic_cast<vault::unify::ConsTerm*>( pAbstractTerm ), pGoal );
        out_pClause = pClause;
    }
    return 0;
}


